// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// platform selection removed; web-only config

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
      return web;
  }
  static FirebaseOptions get web => FirebaseOptions(
        apiKey: 'AIzaSyA_QV7KmJkH620d-OOhP5hk99fdP9ReiyE',
        appId: '1:565446352185:web:bcddd55962106873de1ce8',
        messagingSenderId: '565446352185',
        projectId: 'hire-me-28191',
        authDomain: 'hire-me-28191.firebaseapp.com',
        storageBucket: 'hire-me-28191.firebasestorage.app',
      );
}
